#! /bin/sh

xrandr --output DP-0 --mode 1920x1080 --rate 144 --pos 0x0 --rotate left
xrandr --output HDMI-0 --primary --mode 2560x1440 --rate 144 --pos 1080x180

wmname LG3D

# xset s off -dpms
xset s noblank

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O HDMI-0 DP-0

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10

bspc config border_width         3
bspc config normal_border_color	 "#1e1e2e"
bspc config focused_border_color "#f2cdcd"
bspc config window_gap           5

bspc config automatic_scheme	 alternate
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer false
bspc config pointer_motion_interval 7ms

bspc config ignore_ewmh_focus true

bspc rule -r '*'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Steam state=floating
bspc rule -a discord desktop=10 split_dir=south split_ratio=0.35 follow=on
bspc rule -a Spotify desktop=10 split_dir=north split_ratio=0.35 private=on follow=on
bspc rule -a Pavucontrol state=floating
#bspc rule -a obsidian desktop=^10 follow=off locked=on
bspc rule -a firefox desktop=1 follow=on
bspc rule -a kitty desktop=2 follow=on

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

setxkbmap -option ctrl:swapcaps
xcape -e 'Control_L=Escape'

xsetroot -cursor_name left_ptr

killall polybar
polybar -r main &
polybar -r second &

picom --daemon &

pgrep bspswallow || bspswallow &

#shuf -e -n 1 $HOME/.wallpapers/Custom/* | xargs feh --no-fehbg --bg-fill &
feh --no-fehbg --bg-fill $HOME/.wallpapers/pixel-art-pagoda.png
killall dunst
dunst &

#copyq &

pgrep redshift || redshift &

gwe --hide-window &

#sudo tuxclockerd &

pulseeffects --gapplication-service &

#xfce4-power-manager &

/usr/lib/kdeconnectd &
kdeconnect-indicator &
kdeconnect-battery.sh &

pgrep deej || deej -c /home/mateusz/.config/deej/config.yaml &

playerctld &

killall xidlehook
xidlehook --not-when-audio --not-when-fullscreen --timer 600 'betterlockscreen -l' '' --timer 300 'systemctl suspend' '' &

discord --start-minimized &

# obsidian &
