#! /bin/sh

#xrandr --output eDP --primary --mode 2160x1440 --rate 60
#xrandr --output HDMI-A-0 --mode 2560x1440 --rate 60 --above eDP

#xset s off -dpms
#xset s noblank
xset dpms 300 300 300

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

export QT_QPA_PLATFORMTHEME=qt5ct
export DESKTOP_SESSION=bspwm

#export $(dbus-launch)

pgrep -x sxhkd > /dev/null || sxhkd &

bspwm-monitors.sh

#bspc monitor eDP -d 1 2 3 4 5
#bspc monitor HDMI-A-0 -d 6 7 8 9 10

bspc desktop 1 -l monocle
bspc desktop 2 -l monocle
bspc desktop 3 -l monocle
bspc desktop 4 -l monocle
bspc desktop 5 -l monocle
bspc desktop 6 -l monocle
bspc desktop 7 -l monocle
bspc desktop 8 -l monocle
bspc desktop 9 -l monocle
bspc desktop 10 -l monocle

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width         3
bspc config normal_border_color	 "#1e1e2e"
bspc config focused_border_color "#f2cdcd"
bspc config window_gap           5

bspc config automatic_scheme	 alternate
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focus_follows_pointer false
bspc config pointer_motion_interval 7ms

bspc config ignore_ewmh_focus true

bspc rule -r '*'

bspc rule -a Steam state=floating
bspc rule -a discord desktop=^6
bspc rule -a Spotify desktop=^6
bspc rule -a Pavucontrol state=floating
bspc rule -a firefox desktop=1 -o follow=on
bspc rule -a kitty desktop=2 -o follow=on
bspc rule -a Blueman-manager state=floating

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xsetroot -cursor_name left_ptr

setxkbmap -option ctrl:swapcaps
xcape -e 'Control_L=Escape'

xinput set-prop "GXTP7863:00 27C6:01E0 Touchpad" 298 1
xinput set-prop "GXTP7863:00 27C6:01E0 Touchpad" 329 1

killall polybar
polybar -r main &
polybar -r second &

compfy --daemon &

pgrep bspswallow || bspswallow &

#shuf -e -n 1 $HOME/.wallpapers/Custom/* | xargs feh --no-fehbg --bg-fill &
feh --no-fehbg --bg-fill $HOME/.wallpapers/garrys-mod-train-fox_upscayl_4x_ultrasharp-2.0.1.jpg 

killall dunst
dunst &

pgrep redshift || redshift &

#xfce4-power-manager &

/usr/lib/kdeconnectd &
kdeconnect-indicator &
# indicator-kdeconnect & -- stopped working for some reason

playerctld &

killall xidlehook
xidlehook --not-when-audio --not-when-fullscreen --timer 600 'betterlockscreen -l' '' --timer 300 'systemctl suspend' '' --socket "/tmp/xidlehook.sock" &

fusuma &
