#! /bin/sh

# bspwm-monitors.sh
xrandr --output HDMI-0 --primary --mode 2560x1440 --rate 144 --pos 1080x250
xrandr --output DP-0 --mode 1920x1080 --rate 144 --pos 0x0 --rotate left

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O HDMI-0 DP-0

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10

# bspc desktop 1 -l monocle
# bspc desktop 2 -l monocle
# bspc desktop 3 -l monocle
# bspc desktop 4 -l monocle
# bspc desktop 5 -l monocle

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config border_width         2
bspc config normal_border_color	 "#1e1e2e"
bspc config focused_border_color "#f2cdcd"
bspc config window_gap           5

bspc config automatic_scheme	 alternate
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer false
bspc config pointer_motion_interval 7ms

bspc config ignore_ewmh_focus true

bspc rule -r '*'

# bspc rule -a Steam state=floating
bspc rule -a Zotero state=floating center=on
bspc rule -a discord desktop=10 split_dir=south split_ratio=0.38 follow=on
bspc rule -a Spotify desktop=10 split_dir=north split_ratio=0.38 private=on follow=on
bspc rule -a Pavucontrol state=floating
#bspc rule -a obsidian desktop=^10 follow=off locked=on
bspc rule -a firefox desktop focused:'^1' follow=on
bspc rule -a kitty desktop focused:'^2' follow=on
bspc rule -a Blueman-manager state=floating
bspc rule -a zenity state=floating
bspc rule -a tag_studio.py:'Add Tags' state=floating

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# setxkbmap -option ctrl:swapcaps
# xcape -e 'Control_L=Escape' -t 150

# xsetroot -cursor_name left_ptr

killall polybar
polybar -r main &
polybar -r second &

# compfy --daemon &
picom --daemon &

# pgrep bspswallow || bspswallow &

#shuf -e -n 1 $HOME/.wallpapers/Custom/* | xargs feh --no-fehbg --bg-fill &
feh --no-fehbg --bg-fill $HOME/.wallpapers/wall/in-the-early-morning-of-forest-3840x2501.jpg #--bg-fill --geometry +1350+0 $HOME/.wallpapers/wall/forest-fall-2560×1440.jpg
killall dunst
dunst &

#copyq &

redshift -x && redshift &

gwe --hide-window &

#sudo tuxclockerd &

# pulseeffects --gapplication-service &
easyeffects --gapplication-service &

#xfce4-power-manager &

/usr/bin/kdeconnectd &
kdeconnect-indicator &
kdeconnect-battery.sh &

pgrep deej || deej -c /home/mateusz/.config/deej/config.yaml &

playerctld &

# blueman-applet &

killall xidlehook
# xidlehook --not-when-fullscreen --timer 300 'betterlockscreen -l --off 300' '' &
#--timer 600 'xset s activate' '' &
#--timer 300 'systemctl suspend' '' &

discord --start-minimized &

# obsidian &
